packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
patchedDependencies:
  '@react-pdf/textkit@6.3.0': patches/@react-pdf__textkit@6.3.0.patch
