import type { JobSource } from "./types";
import { HARVESTED } from "./harvested";
import { tencentSource } from "./tencent";
import { bytedanceSource } from "./bytedance";
import { liepinSource } from "./liepin";
import { bossSource } from "./boss";
import { greenSource } from "./green";
import { indeedSource } from "./indeed";
import { indeedGlobalSource } from "./indeedGlobal";
import { wantedlySource } from "./wantedly";
import { remoteokSource } from "./remoteok";
import { hackernewsSource } from "./hackernews";
import {
  neteaseSource,
  riotgamesSource,
  scopelySource,
  kraftonSource,
  nintendoSource,
  bandainamcoSource,
  epicgamesSource,
  taketwoSource,
  nordeusSource,
  bungieSource,
  woogaSource,
  remedySource,
  bethesdaSource,
  housemarqueSource,
} from "./greenhouse";
import {
  sofiSource, brexSource, chimeSource, monzoSource, n26Source, upgradeSource,
  affirmSource, mercurySource, coinbaseSource, oscarSource, ethosSource,
  point72Source, imcSource, wintonSource, janestreetSource, mangroupSource,
  jumptradingSource, flowtradersSource, tideSource, adyenSource, payoneerSource,
  robinhoodSource, schonfeldSource, exoduspointSource, virtuSource, pinganSource, efundSource, cmbSource,
} from "./finance";
import { mihoyoSource } from "./mihoyo";
import { kuroSource } from "./kuro";
import {
  stripeSource, datadogSource, figmaSource, cloudflareSource, twilioSource, gitlabSource,
  oktaSource, zscalerSource, mongodbSource, databricksSource, fastlySource, anthropicSource,
  discordSource, pinterestSource, redditSource, twitchSource, lyftSource, instacartSource,
  geminiSource, courseraSource, duolingoSource, airbnbSource, tripadvisorSource,
  webflowSource, disneySource, cockroachlabsSource, planetscaleSource, clickhouseSource,
  pelotonSource, ouraSource, calmSource, waymoSource, figureaiSource, watershedSource,
  redwoodmaterialsSource, udemySource, udacitySource, masterclassSource, kayakSource,
  flexportSource, newrelicSource, honeycombSource, sigmacomputingSource, amplitudeSource,
  mixpanelSource, robloxSource,
  openaiSource, cohereSource, perplexitySource, elevenlabsSource, characterSource, replitSource,
  runwaySource, mercorSource, fireworksSource, lambdaSource, cursorSource,
  supercellSource, ghostSource, xaiSource, stabilityaiSource, thinkingmachinesSource,
} from "./tech";
import { spotifySource, binanceSource, angellistSource, theAthleticSource, houzzSource } from "./lever";

// 新增来源：实现 JobSource 后在此注册。
export const SOURCES: Record<string, JobSource> = {
  ...HARVESTED,
  [tencentSource.id]: tencentSource,
  [bytedanceSource.id]: bytedanceSource,
  [liepinSource.id]: liepinSource,
  [bossSource.id]: bossSource,
  [greenSource.id]: greenSource,
  [indeedSource.id]: indeedSource,
  [indeedGlobalSource.id]: indeedGlobalSource,
  [wantedlySource.id]: wantedlySource,
  [remoteokSource.id]: remoteokSource,
  [hackernewsSource.id]: hackernewsSource,
  [neteaseSource.id]: neteaseSource,
  [mihoyoSource.id]: mihoyoSource,
  [kuroSource.id]: kuroSource,
  // 游戏公司（Greenhouse 官方招聘板）
  [riotgamesSource.id]: riotgamesSource,
  [scopelySource.id]: scopelySource,
  [kraftonSource.id]: kraftonSource,
  [nintendoSource.id]: nintendoSource,
  [bandainamcoSource.id]: bandainamcoSource,
  [epicgamesSource.id]: epicgamesSource,
  [taketwoSource.id]: taketwoSource,
  [nordeusSource.id]: nordeusSource,
  [bungieSource.id]: bungieSource,
  [woogaSource.id]: woogaSource,
  [remedySource.id]: remedySource,
  [bethesdaSource.id]: bethesdaSource,
  [housemarqueSource.id]: housemarqueSource,
  // 金融：银行 / 保险 / 基金（Greenhouse + best-effort 中文官网）
  [sofiSource.id]: sofiSource,
  [brexSource.id]: brexSource,
  [chimeSource.id]: chimeSource,
  [monzoSource.id]: monzoSource,
  [n26Source.id]: n26Source,
  [upgradeSource.id]: upgradeSource,
  [affirmSource.id]: affirmSource,
  [mercurySource.id]: mercurySource,
  [coinbaseSource.id]: coinbaseSource,
  [oscarSource.id]: oscarSource,
  [ethosSource.id]: ethosSource,
  [point72Source.id]: point72Source,
  [imcSource.id]: imcSource,
  [wintonSource.id]: wintonSource,
  [janestreetSource.id]: janestreetSource,
  [mangroupSource.id]: mangroupSource,
  [jumptradingSource.id]: jumptradingSource,
  [flowtradersSource.id]: flowtradersSource,
  [tideSource.id]: tideSource,
  [adyenSource.id]: adyenSource,
  [payoneerSource.id]: payoneerSource,
  [robinhoodSource.id]: robinhoodSource,
  [schonfeldSource.id]: schonfeldSource,
  [exoduspointSource.id]: exoduspointSource,
  [virtuSource.id]: virtuSource,
  [pinganSource.id]: pinganSource,
  [efundSource.id]: efundSource,
  [cmbSource.id]: cmbSource,
  // 美国科技 / AI / 社交 / 出行 / 电商 / 教育 / 旅游 / 加密（Greenhouse 官方招聘板，实网验证 2026-07-27）
  [stripeSource.id]: stripeSource,
  [datadogSource.id]: datadogSource,
  [figmaSource.id]: figmaSource,
  [cloudflareSource.id]: cloudflareSource,
  [twilioSource.id]: twilioSource,
  [gitlabSource.id]: gitlabSource,
  [oktaSource.id]: oktaSource,
  [zscalerSource.id]: zscalerSource,
  [mongodbSource.id]: mongodbSource,
  [databricksSource.id]: databricksSource,
  [fastlySource.id]: fastlySource,
  [anthropicSource.id]: anthropicSource,
  [discordSource.id]: discordSource,
  [pinterestSource.id]: pinterestSource,
  [redditSource.id]: redditSource,
  [twitchSource.id]: twitchSource,
  [lyftSource.id]: lyftSource,
  [instacartSource.id]: instacartSource,
  [geminiSource.id]: geminiSource,
  [courseraSource.id]: courseraSource,
  [duolingoSource.id]: duolingoSource,
  [airbnbSource.id]: airbnbSource,
  [tripadvisorSource.id]: tripadvisorSource,
  // 第二轮扩充（设计 / 媒体 / 数据库 / 健康 / 气候 / 教育 / 旅游 / 物流 / 数据分析 / 游戏）
  [webflowSource.id]: webflowSource,
  [disneySource.id]: disneySource,
  [cockroachlabsSource.id]: cockroachlabsSource,
  [planetscaleSource.id]: planetscaleSource,
  [clickhouseSource.id]: clickhouseSource,
  [pelotonSource.id]: pelotonSource,
  [ouraSource.id]: ouraSource,
  [calmSource.id]: calmSource,
  [waymoSource.id]: waymoSource,
  [figureaiSource.id]: figureaiSource,
  [watershedSource.id]: watershedSource,
  [redwoodmaterialsSource.id]: redwoodmaterialsSource,
  [udemySource.id]: udemySource,
  [udacitySource.id]: udacitySource,
  [masterclassSource.id]: masterclassSource,
  [kayakSource.id]: kayakSource,
  [flexportSource.id]: flexportSource,
  [newrelicSource.id]: newrelicSource,
  [honeycombSource.id]: honeycombSource,
  [sigmacomputingSource.id]: sigmacomputingSource,
  [amplitudeSource.id]: amplitudeSource,
  [mixpanelSource.id]: mixpanelSource,
  [robloxSource.id]: robloxSource,
  // Ashby 招聘板（AI / 大模型 / 游戏厂，实网验证 2026-08-01）
  [openaiSource.id]: openaiSource,
  [cohereSource.id]: cohereSource,
  [perplexitySource.id]: perplexitySource,
  [elevenlabsSource.id]: elevenlabsSource,
  [characterSource.id]: characterSource,
  [replitSource.id]: replitSource,
  [runwaySource.id]: runwaySource,
  [mercorSource.id]: mercorSource,
  [fireworksSource.id]: fireworksSource,
  [lambdaSource.id]: lambdaSource,
  [cursorSource.id]: cursorSource,
  [supercellSource.id]: supercellSource,
  [ghostSource.id]: ghostSource,
  // Greenhouse 的 AI 板（实网验证 2026-08-01）
  [xaiSource.id]: xaiSource,
  [stabilityaiSource.id]: stabilityaiSource,
  [thinkingmachinesSource.id]: thinkingmachinesSource,
  // Lever 招聘板（公开 JSON，无鉴权）
  [spotifySource.id]: spotifySource,
  [binanceSource.id]: binanceSource,
  [angellistSource.id]: angellistSource,
  [theAthleticSource.id]: theAthleticSource,
  [houzzSource.id]: houzzSource,
};

export const SOURCE_IDS = Object.keys(SOURCES);
