/**
 * 读取 /tmp/harvest_ok.txt，筛选优质公司，生成 sources/harvested.ts。
 * 阈值：jobs>=25；排除 applyto 招聘代理 / 结尾 -数字 重复快照 / internship 类。
 */
import fs from "node:fs";

const SRC = "/tmp/harvest_ok.txt";
const OUT = "/Users/hebeihang/DEV/tools/careeros/apps/worker/src/sources/harvested.ts";
const MIN = 25;

function pretty(s: string): string {
  return s.replace(/[-_.]+/g, " ").trim().replace(/\b\w/g, (c) => c.toUpperCase());
}

const lines = fs.readFileSync(SRC, "utf8").trim().split("\n").filter(Boolean);
const rows = lines.map((l) => {
  const p = l.split("\t");
  return { id: p[1], kind: p[2], category: p[3], jobs: +p[4] } as {
    id: string; kind: string; category: string; jobs: number;
  };
});

const sel = rows.filter(
  (r) => r.jobs >= MIN && !/applyto|intern/i.test(r.id) && !/-\d+$/.test(r.id),
);
const map = new Map<string, typeof sel[number]>();
for (const r of sel) if (!map.has(r.id)) map.set(r.id, r);
const items = [...map.values()].sort((a, b) => b.jobs - a.jobs);

const rawLines = items
  .map((r) => `  { id: ${JSON.stringify(r.id)}, label: ${JSON.stringify(pretty(r.id))}, kind: ${JSON.stringify(r.kind)}, category: ${JSON.stringify(r.category)} },`)
  .join("\n");

const file = `// AUTO-GENERATED by scripts/gen-harvested.ts — do not edit by hand.
// 来源清单来自 openapply 真实 slug 库 + 实网验证（jobs>=25 的活跃公司）。
import { makeGreenhouseSource } from "./greenhouse";
import { makeAshbySource } from "./ashby";
import { makeLeverSource } from "./lever";
import type { JobSource } from "./types";

interface Raw {
  id: string;
  label: string;
  kind: "greenhouse" | "ashby" | "lever";
  category: "tech" | "game" | "finance" | "ai" | "general";
}

const raw: Raw[] = [
${rawLines}
];

export const HARVESTED: Record<string, JobSource> = {};
for (const r of raw) {
  if (r.kind === "greenhouse")
    HARVESTED[r.id] = makeGreenhouseSource({ id: r.id, label: r.label, board: r.id, category: r.category });
  else if (r.kind === "ashby")
    HARVESTED[r.id] = makeAshbySource({ id: r.id, label: r.label, org: r.id, category: r.category });
  else
    HARVESTED[r.id] = makeLeverSource({ id: r.id, label: r.label, company: r.id, category: r.category });
}

export const HARVESTED_IDS = Object.keys(HARVESTED);
`;

fs.writeFileSync(OUT, file);

// 统计
const byKind: Record<string, number> = {};
const byCat: Record<string, number> = {};
for (const r of items) {
  byKind[r.kind] = (byKind[r.kind] ?? 0) + 1;
  byCat[r.category] = (byCat[r.category] ?? 0) + 1;
}
console.log(`已生成 harvested.ts: ${items.length} 个来源`);
console.log("按板:", byKind);
console.log("按品类:", byCat);
console.log("Top 10:", items.slice(0, 10).map((r) => `${r.id}(${r.jobs})`).join(", "));
